### ISSUE TITLE
make repo of plan spinets 

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#125]
This way we can share plans (and update them).

**Comment by sbillinge** [comment]
THis is a great idea

This will need the repo, a workflow, and documentation on how to use it.

Perhaps we could release an alpha version that doesn't have the workflow and documentation to just "expert" users this cycle, and roll it out in full later?

**Comment by st3107** [comment]
We have a repo of the plans.

https://github.com/Billingegroup/bluesky_scanplans

I moved the automated shutter control outsides the plans so that users do not need to worry about the shutter when they designed the plan. When they said `trigger_and_read`, the shutter will open and close automatically. Thus, I recommend users use the `bluesky.plans` module more instead of writing their own.
