### ISSUE TITLE
detector switch : configure image_field at analysis window

### ISSUE THREAD

**Issue by adelezh** [xpdAcq/mission-control#136]
Can we configure image_field at analysis window instead of edit xpd.yml at /.config/acq/

**Comment by CJ-Wright** [comment]
Ideally this data would be in the start document(maybe?)

**Comment by CJ-Wright** [comment]
think this is a plan:
1. We chunk the raw data pipelines (see https://github.com/xpdAcq/xpdtools/pull/51)
1. We add the calibration to each detector so that the calibration is now in the descriptors.
1. We produce sub-pipelines for each detector. Each sub-pipeline pulls the calibration from the descriptor. Note that this means we need to handle stop documents in SHED elegantly, since it is very possible that we will get no data through a pipeline (eg we only ran with 1 detector but three are registered). There are two potential outcomes, we either issue a start and stop with no data or don't issue a start or stop (aka it never happened). I think the second option is best since we don't create a bunch of useless headers. This means that on stop document we need to check if any data entered the pipeline (including buffers). If nothing came in then we don't issue any documents. Note that we should add the available detectors to the start document so we know what pipelines to build.

This approach also helps with the "use multiple detectors at once use case" and so might be a good overall approach.
