### ISSUE TITLE
Consistency of area detector configuration in acquisition and analysis side

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/mission-control#152]
In order to have data saved by the pipeline, the `image_field` value in the analysis side (stored in `glbl` dict object) must be the same as the area detector triggered at acquisition side. 

As we are changing detector more often now, this problem could happen quite often. Might relate to #136.

## Expected Behavior
change area detector in use in the acquisition side `xpd_configuration['area_det'] = pe1c`
and `image_field` in the analysis side is updated automatically.

## Current Behavior
After change the detector in the acquisition side, we need to stop the pipeline, exit out analysis terminal, edit a local config file and restart the pipeline. 

If the user doesn't do that, image won't be saved by the pipeline. This sometimes causes panic since user can see diffraction pattern in the CS studio but data is not saved and no error from both acq and analysis side.

**Comment by CJ-Wright** [comment]
For the analysis side I think a good way to implement this is to have the area detectors which are being used in the start document somewhere. When we go to build the pipeline we can inspect that start document so that we can pull the data from the appropriate field(s). This way the pipeline doesn't depend on a detector configuration set elsewhere.
