### ISSUE TITLE
MTN: make release checklist

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#37]
Make a checklist for releasing code for easier operations.

**Comment by sbillinge** [comment]
@CJ-Wright YES!!!! love checklists!

**Comment by CJ-Wright** [comment]
Might even make this into a script so that we automatically check our releases (rever does this well).

**Comment by sbillinge** [comment]
assigning this to @chiahaoliu in consultation with Chris.

**Comment by sbillinge** [comment]
yes, can we use that?  How do we make sure that all the bullets are done?  we can put in validation steps?

**Comment by sbillinge** [comment]
what is happening here?  @chiahaoliu are you starting a list of the things we need in our checklist?  Here are some things I think we need to address:

1) Where will the checklist be and in what form.  Even if it is a set of rever steps we need a document that says something like "xpdAcq installation instructions"  with content "run rever" or sthg.    This is important because the people who install xpdAcq will change with time.  So the decision of where to put this checklist is important.  It needs to be in a place that is discoverable and memorable, like `xpd-dev` or the README in xpdAcq repo, or both.  In fact, how about making the decision that it will be both of these, where the xpd-dev one points to the README (i.e., don't maintain documentation in two places, but do make it discoverable from two places).

2) Is this list complete or @chiahaoliu  are you still working on it?  Do you want more feedback/input?  The best times to make these lists are when the installation is taking place.  And the very best way is for one of the dev's to write the documentation and have a novice (or target audience) follow the docs to do the installation with the dev looking on, and fixing the docs whenever the novice gets stuck.

**Comment by st3107** [comment]
I made the bash script for installation (a script called `install.sh` in the repos) and the xonsh script for rever release. I think if we can make it simple as running one command in a terminal, we will do that instead of writing a one-page-long document. The novice can open the script file and see those lines with comments. They will know what happened during the installation and release.
