### ISSUE TITLE
ENH: overplot button

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#73]
If button pushed don't clear on start.

**Comment by CJ-Wright** [comment]
May need to move this to cycle 2.

**Comment by sbillinge** [comment]
ok done

**Comment by CJ-Wright** [comment]
I think we should get the DAMA group in on this, since this may be best fixed at the callback layer (esp as we are trying to move to best effort callback as our omnibus visualization tool).

**Comment by sbillinge** [comment]
@CJ-Wright I'm more than ok with this.

On the whole, I think that the "overplot" button won't work well, because people won't know/remember to set that button until the new run starts and their old plots disappear, and then it is too late.

I think better behavior is give an ability to have some data analysis capabilities that are not running live, so that they have great flexibility to graph what they want, and the live-plotting is just doing simple stuff.
